chore: fix deployment script and try without zip

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -9,65 +9,46 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: CD to Lambda
-        run: pwd && cd cdk/lambda && pwd && ls
-      - name: list files
-        run: ls && pwd
-      - name: CD into CDK dir
-        run: cd .. && pwd && ls
-  #     - name: Detect package manager
-  #       id: detect-package-manager
-  #       run: |
-  #         if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-  #           echo "manager=yarn" >> $GITHUB_OUTPUT
-  #           echo "command=install" >> $GITHUB_OUTPUT
-  #           echo "runner=yarn" >> $GITHUB_OUTPUT
-  #           exit 0
-  #         elif [ -f "${{ github.workspace }}/package.json" ]; then
-  #           echo "manager=npm" >> $GITHUB_OUTPUT
-  #           echo "command=ci" >> $GITHUB_OUTPUT
-  #           echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-  #           exit 0
-  #         else
-  #           echo "Unable to determine package manager"
-  #           exit 1
-  #         fi
-  #     - name: Setup Node
-  #       uses: actions/setup-node@v3
-  #       with:
-  #         node-version: 18
-  #         cache: ${{ steps.detect-package-manager.outputs.manager }}
-  #     - name: Restore cache
-  #       uses: actions/cache@v3
-  #       with:
-  #         path: |
-  #           .next/cache
-  #         # Generate a new cache whenever packages or source files change.
-  #         key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
-  #         # If source files changed but packages didn't, rebuild from a prior cache.
-  #         restore-keys: |
-  #           ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
-  #     - name: Install dependencies
-  #       run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-  #     - name: CD into CDK dir
-  #       run: cd .. && pwd && ls
-  #     - name: Zip Lambda
-  #       run: zip -r lambda.zip lambda && ls
-  #     - name: CD into Root
-  #       run: cd ../
-  #     - name: CDK Deploy
-  #       uses: youyo/aws-cdk-github-actions@v2
-  #       with:
-  #         cdk_subcommand: 'deploy'
-  #         cdk_stack: 'CodeGptStack'
-  #         cdk_args: '--require-approval never'
-  #         actions_comment: false
-  #         working_dir: 'cdk'
-  #       env:
-  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         AWS_DEFAULT_REGION: 'us-east-1'
-  #         CDK_DEFAULT_ACCOUNT: ${{ env.CDK_DEFAULT_ACCOUNT }}}
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          cd cdk/lambda
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 18
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Install dependencies
+        run: | 
+          cd cdk/lambda
+          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: CDK Deploy
+        uses: youyo/aws-cdk-github-actions@v2
+        with:
+          cdk_subcommand: 'deploy'
+          cdk_stack: 'CodeGptStack'
+          cdk_args: '--require-approval never'
+          actions_comment: false
+          working_dir: 'cdk'
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: 'us-east-1'
+          CDK_DEFAULT_ACCOUNT: ${{ env.CDK_DEFAULT_ACCOUNT }}}
   # deploy_webapp:
   #   name: Deploy Webapp
   #   needs: deploy_cdk
