feat: add test pipeline

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -3,54 +3,63 @@ on:
   push: 
     branches: [ master ]
 jobs:
-  deploy_cdk:
-    name: Deploy CDK
+  test_lambda:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-      - name: Detect package manager
-        id: detect-package-manager
+      - name: Install packages
         run: |
-          cd cdk/lambda
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
-      - name: Install dependencies
-        run: | 
-          cd cdk/lambda
-          npm install typescript
-          npm run transpile-two
-          ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-      - name: CDK Deploy
-        uses: youyo/aws-cdk-github-actions@v2
-        with:
-          cdk_subcommand: 'deploy'
-          cdk_stack: 'CodeGptStack'
-          cdk_args: '--require-approval never'
-          actions_comment: false
-          working_dir: 'cdk'
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: 'us-east-1'
-          CDK_DEFAULT_ACCOUNT: ${{ env.CDK_DEFAULT_ACCOUNT }}}
+          npm ci
+          npm run test
+  # deploy_cdk:
+  #   name: Deploy CDK
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #     - name: Detect package manager
+  #       id: detect-package-manager
+  #       run: |
+  #         cd cdk/lambda
+  #         if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+  #           echo "manager=yarn" >> $GITHUB_OUTPUT
+  #           echo "command=install" >> $GITHUB_OUTPUT
+  #           echo "runner=yarn" >> $GITHUB_OUTPUT
+  #           exit 0
+  #         elif [ -f "${{ github.workspace }}/package.json" ]; then
+  #           echo "manager=npm" >> $GITHUB_OUTPUT
+  #           echo "command=ci" >> $GITHUB_OUTPUT
+  #           echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+  #           exit 0
+  #         else
+  #           echo "Unable to determine package manager"
+  #           exit 1
+  #         fi
+  #     - name: Setup Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 18
+  #         cache: ${{ steps.detect-package-manager.outputs.manager }}
+  #     - name: Install dependencies
+  #       run: | 
+  #         cd cdk/lambda
+  #         npm install typescript
+  #         npm run transpile-two
+  #         ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+  #     - name: CDK Deploy
+  #       uses: youyo/aws-cdk-github-actions@v2
+  #       with:
+  #         cdk_subcommand: 'deploy'
+  #         cdk_stack: 'CodeGptStack'
+  #         cdk_args: '--require-approval never'
+  #         actions_comment: false
+  #         working_dir: 'cdk'
+  #       env:
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #         AWS_DEFAULT_REGION: 'us-east-1'
+  #         CDK_DEFAULT_ACCOUNT: ${{ env.CDK_DEFAULT_ACCOUNT }}}
   # deploy_webapp:
   #   name: Deploy Webapp
   #   needs: deploy_cdk
